# These are supported funding model platforms

github: safinakib # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: safinakib
open_collective: safinakib # Replace with a single Open Collective username
ko_fi: safinakib # Replace with a single Ko-fi username
tidelift: safinakib # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: safinakib # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: safinakib # Replace with a single Liberapay username
issuehunt: safinakib # Replace with a single IssueHunt username
otechie: safinakib # Replace with a single Otechie username
# lfx_crowdfunding: kicad # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["https://www.paypal.me/octocat", octocat.com , "https://lukesmith.xyz/pix/xmr.png"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

